version: '3.5'

services:
  nodejsapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejsapi
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    #    command: node app.js
    command: node app.js
  #    command: /home/node/app/node_modules/.bin/nodemon app.js
  #    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js


networks:
  app-network:
    driver: bridge
    name: app-network
#    external: true

volumes:
  node_modules: